### ISSUE TITLE
Parse/Syntax Error WPCFG.php Line 78

### ISSUE THREAD

**Issue by Zweihander42** [TypistTech/wp-cloudflare-guard#74] opened 2017-06-29 08:33 UTC
Occasionally getting an error:
`Parse error: syntax error, unexpected '.' in /home/user/site.com/wp-content/plugins/wp-cloudflare-guard/src/WPCFG.php on line 78`

The error came up when running cron updates via wp cli though I think I've seen it happen a couple of times elsewhere (sorry for ambiguity, last time I saw it was during some major theme and plugin updates I did a couple weeks ago and I can't remember the context where it came up).

The error seemed to block a single wp_cron update (and didn't come up subsequently) so not a critical problem from my experience so far. If I see it come up consistently or in another context, I'll update.

On shared hosting, PHP 7.0.14, Ubuntu 12.04.5 LTS.

**Comment by TangRufus** [comment] 2017-06-29 14:24
Thanks for reporting. However, I can't reproduce this error on PHP 7.0 or 7.1.

From the error message, I guess `wp cli` is running on PHP < 5.6
I used [argument unpacking](https://wiki.php.net/rfc/argument_unpacking) on that line and it needs PHP 5.6 or later.

Closing this issue for now because it's non-reproducible. If it comes up again, please check what PHP version `wp cli` is running (it cloud be different from the web server one) and re-open this issue.
Tips: Use [`$ wp cli info`](https://developer.wordpress.org/cli/commands/cli/info/)

**Closed by TangRufus** 2017-06-29 14:24 UTC
Labels: invalid

**Comment by Zweihander42** [comment] 2017-06-30 00:55
Yup, thought I had taken care of that problem but that was it. Thanks for getting back to me! 

For anyone else finding the problem:
The shared hosting I have has 2 versions of PHP. WP CLI was using the 5.6 version in the cron event and the 7.0 version when I SSH'd in. I had added `export WP_CLI_PHP=/path/to/php7` to my bash profile but this didn't apply to the context where the cron event ran.
